[package]
name = "gyra-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
gyra-codec = { version = "0.1.0", path = "../gyra-codec" }
gyra-macros = { version = "0.1.0", path = "../gyra-macros" }
flate2 = "1.0.33"
log = "0.4.22"
